eureka/eureka/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'eureka.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', include('ideas.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^app/', include('ideas.urls')),    
)

eureka/ideas/urls.py
from django.conf.urls import patterns, include, url
from ideas import views
import notifications

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^help$', views.help, name="help"),
    url(r'^inbox/notifications/', include(notifications.urls)),

    # auth urls
    url(r'^login$', views.login, name="login"),
    url(r'^logout$', views.logout, name="logout"),
    url(r'^signup$', views.signup, name="signup"),

    # ideas urls
    url(r'^ideas$', views.ideas, name="ideas"),
    url(r'^ideas/(?P<sort>[a-z]{1,})/$', views.ideas, name="ideas"),
    url(r'^ideas/add$', views.add_idea, name="add_idea"),
    url(r'^ideas/(?P<idea_id>\d+)$', views.idea, name="idea"),
    url(r'^ideas/edit/(?P<idea_id>\d+)$', views.edit_idea, name='edit_idea'),

    # users
    url(r'^users$', views.users, name="users"),
    url(r'^users/(?P<sort>[a-z]{1,})/$', views.users, name="users"),
    url(r'^users/(?P<user_id>\d+)$', views.user, name="user"),
    # url(r'^users/(?P<username>[a-zA-Z0-9@.+-_]{1})$', views.user, name="user"),
    url(r'^users/(?P<user_id>\d+)/(?P<tab>[a-z]{1,})/$', views.user, name="user"),
    url(r'^users/edit$', views.edit_user, name="edit_user"),

    # search
    url(r'^search$', views.search, name="search"),

    # api
    url(r'^api/ideas/delete/(?P<idea_id>\d+)$', views.delete_idea, name="delete_idea"),
    url(r'^api/interest/(?P<idea_id>\d+)$', views.add_interest, name='add_interest'),
    url(r'^api/interest/remove/(?P<idea_id>\d+)$', views.remove_interest, name='remove_interest'),
    url(r'^api/comments/(?P<idea_id>\d+)$', views.add_comment, name="add_comment"),
    url(r'^api/comments/delete/(?P<comment_id>\d+)$', views.delete_comment, name="delete_comment"),
    url(r'^api/comments/edit/(?P<comment_id>\d+)$', views.edit_comment, name="edit_comment"),
    url(r'^api/ideas/like/(?P<idea_id>\d+)$', views.like, name="like"),
    url(r'^api/ideas/dislike/(?P<idea_id>\d+)$', views.dislike, name="dislike"),
    url(r'^api/ideas/state/(?P<idea_id>\d+)/(?P<state>[ARI]{1})$', views.change_state, name="change_state"),
    url(r'^api/tags$', views.tags, name="tags"),
    url(r'^api/notifications/mark_all_as_read$', views.notify_mark_all_as_read, name="mark_all_as_read"),
)

eureka/ideas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from taggit.managers import TaggableManager

import datetime

# Create your models here.

class Idea(models.Model):
    STATE_CHOICES = (
        ('A', 'Approved'),
        ('R', 'Rejected'),
        ('I', 'Idle')
    )

    user = models.ForeignKey(User)
    title = models.CharField(max_length=160)
    text = models.TextField()
    state = models.CharField(max_length=1, choices=STATE_CHOICES, default='I')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    views = models.IntegerField(default=0)
    tags = TaggableManager(blank=True)

    def __unicode__(self):
        return "{user.username}: {title}".format(
            user=self.user, title=self.title)

    def was_added_recently(self):
        """
        returns true if the idea was added in the last 3 days
        """
        return self.created >= timezone.now() - datetime.timedelta(days=3);

    def was_edited(self):
        return (self.updated - self.created) > datetime.timedelta(seconds=1)


class Comment(models.Model):
    user = models.ForeignKey(User)
    idea = models.ForeignKey(Idea)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "%s said %s" % (self.user.username, self.text[:160])

    def was_edited(self):
        return (self.updated - self.created) > datetime.timedelta(seconds=1)


class Like(models.Model):
    user = models.ForeignKey(User)
    idea = models.ForeignKey(Idea)
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return "{user} liked {idea}".format(user=self.user.username, idea=self.idea.title)


class Interest(models.Model):
    user = models.ForeignKey(User)
    idea = models.ForeignKey(Idea)
    created = models.DateTimeField(auto_now_add=True, default=timezone.now())

    def __unicode__(self):
        return "%s is interested in %s" % (self.user.username, self.idea.title)

eureka/ideas/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from ideas.models import Idea
from ideas.models import Comment
from taggit.forms import *
from django import forms


ALLOWED_ALIAS = [ "aferreira", "jpgomes", "dviana", "ttavares", "mbarreira",
    "agomes", "arobalo", "ppires", "stavares", "lcosta", "ttrindade",
    "bpinto", "cscosta", "jhenriques", "gdias", "ccarvalheira",
    "afigueiroa", "mcarvalho", "tvieira", "lcouto", "rmrodrigues",
    "rfonte", "dacastro", "imota", "hferrolho", "langelo",
    "dsousa", "amsoliveira", "rleal"
]


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    def clean_email(self):
        """
        Validate that the supplied email address is unique and belongs
        to a restricted set of addresses.
        """

        email = self.cleaned_data['email']

        if email.split('@')[0] not in ALLOWED_ALIAS:
            raise forms.ValidationError("You don't have permission to access this application")

        if User.objects.filter(email__iexact=email).count():
            raise forms.ValidationError('This email address is already in use. Please supply a different email address.')

        return email

    class Meta:
        model = User
        fields = ( "username", "email", "password1", "password2")


class IdeaForm(ModelForm):
    class Meta:
        model = Idea
        fields = ['title', 'text', 'tags']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

eureka/ideas/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from ideas.models import Idea
from ideas.models import Interest
from ideas.models import Comment
from ideas.models import Like
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import PasswordChangeForm
from django.utils import timezone
from ideas.forms import UserCreationForm
from ideas.forms import IdeaForm
from ideas.forms import CommentForm
from taggit.models import Tag
from notifications import notify

import datetime
import json


def index(request):
    if request.user.is_authenticated():
        return redirect('ideas')
    return render(request, 'ideas/index.html')


def help(request):
    return render(request, 'ideas/help.html')


def login(request):
    if request.method == 'GET':
        if request.user.is_authenticated():
            return redirect('user', user_id=request.user.id)
        return render(request, 'ideas/auth/login.html')
    elif request.method == 'POST':
        login_form = AuthenticationForm(data=request.POST)

        if request.POST and login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect('index')

        return render(request, 'ideas/auth/login.html', 
            {'login_form': login_form})


def logout(request):
    auth_logout(request)
    return redirect('index')


def signup(request):
    if request.method == 'GET':
        return render(request, 'ideas/auth/signup.html')
    elif request.method == 'POST':
        user_form = UserCreationForm(request.POST)

        if user_form.is_valid():
            username = user_form.clean_username()
            password = user_form.clean_password2()
            user_form.clean_email()
            user = user_form.save(commit=False)
            user.is_active = True
            user.save()

            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('ideas')
            else:
                return HttpResponse('Invalid login.')
            
        else:
            return render(request, 'ideas/auth/signup.html',
                {'form': user_form})


@login_required(login_url='login')
def ideas(request, sort='latest'):
    valid_sorts = ['latest', 'popular', 'approved', 'rejected']
    if sort not in valid_sorts:
        sort = 'latest'

    if sort == 'latest':
        ideas = Idea.objects.order_by('-created')
    elif sort == 'popular':
        ideas = Idea.objects.annotate(num_interest=Count('interest'))\
            .filter(num_interest__gt=0)\
            .order_by('-num_interest')
    elif sort == 'approved':
        ideas = Idea.objects.filter(state='A').order_by('-created')
    else:
        ideas = Idea.objects.filter(state='R').order_by('-created')

    # paginate the results
    paginator = Paginator(ideas, 20)
    page = request.GET.get('page')

    try:
        ideas = paginator.page(page)
    except PageNotAnInteger:
        ideas = paginator.page(1)
    except EmptyPage:
        ideas = paginator.page(paginator.num_pages)

    return render(request, 'ideas/ideas/list.html',
        {'idea_list': ideas, 'sort': sort})


@login_required(login_url='login')
def idea(request, idea_id):
    idea = get_object_or_404(Idea, pk=idea_id)

    return render(request, 'ideas/ideas/view.html', {
        'idea': idea,
        'comments': idea.comment_set.all().order_by('-created'),
        'interested': request.user.interest_set.filter(idea=idea_id),
        'liked': request.user.like_set.filter(idea=idea_id),
    })
      

@login_required(login_url='login')
def add_idea(request):
    if request.method == 'GET': 
        return render(request, 'ideas/ideas/add.html')
    elif request.method == 'POST':
        idea_form = IdeaForm(request.POST)
        
        if idea_form.is_valid():
            new_idea = idea_form.save(commit=False)
            new_idea.user = request.user
            new_idea.save()
            idea_form.save_m2m()
            return redirect("idea", idea_id=new_idea.id)
        else: # needs to show the form with the errors
            return render(request, 'ideas/ideas/add.html',
                {'form': idea_form})


@login_required(login_url='login')
def edit_idea(request, idea_id):
    idea = get_object_or_404(Idea, pk=idea_id)

    if request.user.id == idea.user.id:
        if request.method == 'GET':
            return render(request, 'ideas/ideas/edit.html', {'idea': idea})
        elif request.method == 'POST':
            edit_form = IdeaForm(request.POST)

            if edit_form.is_valid():
                temp = edit_form.save(commit=False)
                temp.id = idea.id
                idea.title = request.POST['title']
                idea.text = request.POST['text']
                idea.updated = timezone.now()
                idea.save()
                edit_form.save_m2m()
                return redirect('idea', idea_id=idea_id)
            else:
                return render(request, 'ideas/ideas/edit.html',
                {'idea': idea, 'form': edit_form})

    return HttpResponse("You don't have permission to edit this question")


@login_required
def edit_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user.id == comment.user.id:
        if request.method == "POST":
            edit_form = CommentForm(request.POST)
            if edit_form.is_valid():
                comment.text = request.POST.get('text')
                comment.save()
                return redirect('idea', idea_id=comment.idea.id)
            else:
                return HttpResponse('This comment is not valid')
    
    return HttpResponse("You don't have permission to edit this comment")

def delete_idea(request, idea_id):
    response = {'status': 'fail'}
    response['data'] = None

    if request.is_ajax():
        if request.user.is_authenticated():
            try:
                idea = Idea.objects.get(pk=idea_id)
                if idea.user.id == request.user.id:
                    idea.delete()
                    response['status'] = 'success'
                else:
                    response['data'] = {'title': "This idea isn't yours"}
            except Idea.DoesNotExist:
                response['data'] = {'title': 'No idea with that id was found'}
        else:
            response['data'] = {'title': 'You must be logged in to delete an idea'}
    else:
        response['data'] = {'title': 'API can only be used with AJAX requests'}
    return HttpResponse(json.dumps(response), content_type="application/json")


@login_required
def delete_comment(request, comment_id):
    if request.method == 'POST':
        try:
            comment = Comment.objects.get(pk=comment_id)
            idea_id = comment.idea.id
            if comment.user == request.user:
                comment.delete()
                return redirect('idea', idea_id=idea_id)
            else:
                return HttpResponse("That comment isn't yours to delete.")
        except Comment.DoesNotExist:
            return HttpResponse('No comment with that id.')


def add_interest(request, idea_id):
    response = {'status': 'fail'}

    if request.is_ajax():
        if request.user.is_authenticated():
            if request.user.interest_set.filter(idea=idea_id):
                response['data'] = {
                    'title': "You're already interested in this question"}
            else:
                try:
                    idea = Idea.objects.get(pk=idea_id)
                    interest = Interest(user=request.user, idea=idea)
                    interest.save()
                    response['status'] = 'success'
                    response['data'] = {
                        'username': request.user.username,
                        'id': request.user.id,
                        'email': request.user.email,
                        'created': interest.created}

                    # generate a notification
                    if request.user != idea.user:
                        notify.send(request.user, recipient=idea.user, verb=u'interested', action_object=interest, description=u'', target=idea)

                except Idea.DoesNotExist:
                    response['data'] = {
                        'title': 'No idea with that id was found'}
        else:
            response['data'] = {
                'title': 'You must be logged in to be interested in an idea'}
    else:
        response['data'] = {'title': 'API can only be used with AJAX requests'}
    return HttpResponse(
        json.dumps(response, cls=DjangoJSONEncoder),
        content_type="application/json")


def remove_interest(request, idea_id):
    response = {'status': 'fail'}

    if request.is_ajax():
        if request.user.is_authenticated():
            if not request.user.interest_set.filter(idea=idea_id):
                response['data'] = {
                    'title': "You're not interested in this question"}
            else:
                interest = Interest.objects.filter(idea=idea_id, user=request.user.id)
                interest.delete()
                response['status'] = 'success'
                response['data'] = None
        else:
            response['data'] = {
                'title': 'You must be logged in to remove interest in an idea'}
    else:

eureka/ideas/templates/ideas/users/base.html
{% extends "ideas/base.html" %}

{% block title %}Eureka - Users{% endblock %}

{% block navbar-links %}

<ul class="nav navbar-nav">
  {% if user.is_authenticated %}
  <li><a href="{% url 'ideas' %}">IDEAS</a></li>
  <li class="active"><a href="{% url 'users' %}">USERS</a></li>
  {% endif %}
</ul>

{% endblock %}

{% block content %}{% endblock %}

eureka/ideas/templates/ideas/users/edit.html
{% extends "ideas/base.html" %}

{% block title %}Eureka - Change password{% endblock %}

{% block content %}
<div class="container">
  <div class="panel panel-default login-panel">
    <div class="panel-body">

      {% if status == 'success' %}
          <div class="alert alert-success">Your password was successfully changed!</div>
      {% else %}
      <h2 class="text-center">Change Password</h2>
      <form class="form-authentication" role="form" action="" method="POST">
        {% csrf_token %}
        <hr>

        <div class="form-group {% if form.error_messages.password_incorrect %}has-error{% endif %}">
          <label for="old_password">Old password</label>
          <input name="old_password" type="password" class="form-control" placeholder="Old password" required>
          <span class="help-block">{{form.error_messages.password_incorrect}}</span>
        </div>

        <div class="form-group {% if form.error_messages.password_mismatch %}has-error{% endif %}">
          <label for="new_password1">New password</label>
          <input name="new_password1" type="password" class="form-control" placeholder="New password" required>
        </div>

        <div class="form-group {% if form.error_messages.password_mismatch %}has-error{% endif %}">
          <label for="confirm_password">Confirm new password</label>
          <input name="new_password2" type="password" class="form-control" placeholder="Confirm new password" required>
          <span class="help-block">{{form.error_messages.password_mismatch}}</span>
        </div>
        <button class="btn btn-lg btn-success btn-block" type="submit">Change password</button>
      </form>
      {% endif %}

    </div>
  </div>
</div> <!-- /container -->

{% endblock %}

eureka/ideas/templates/ideas/users/list.html
{% extends "ideas/users/base.html" %}

{% block title %}Eureka - Users{% endblock %}

{% block content %}

{% load humanize %}
{% load gravatar %}

<div class="sub-navbar">
  <div class="container">
    <h4 class="pull-right hidden-xs">Showing {{ user_list|length}} user{% if user_list|length != 1 %}s{% endif%}</h4>
    {% if user_list|length > 0 %}
    <input class="pull-right" id="find-user-input" type="text" placeholder="Find a user..."></input>
    {% endif %}
    <ul class="nav nav-pills pull-left">
      <li class="{% if sort == 'all' %}active{% endif %}"><a href="{% url 'users' sort='all' %}" title="all users ordered alphabetically">All</a></li>
      <li class="{% if sort == 'latest' %}active{% endif %}"><a href="{% url 'users' sort='latest' %}" title="users that joined in the last 7 days">New users</a></li>
      <li class="{% if sort == 'thinkers' %}active{% endif %}"><a href="{% url 'users' sort='thinkers' %}" title="users with at least 1 idea">Thinkers</a></li>
      <li class="{% if sort == 'commenters' %}active{% endif %}"><a href="{% url 'users' sort='commenters' %}" title="users with at least 1 comment">Commenters</a></li>
    </ul>
  </div>
</div>

<div class="container">

  <div class="row users-list">
    <div class="col-md-12">

      {% if user_list|length == 0%}
      <p class="lead">Ooops, we don't have any users to show you.</p>
      {% else %}

      {% for user in user_list %}
      <div class="user">
        <div class="media">
          <a class="pull-left" href="#">
            <img class="media-object" src="{% gravatar_url user.email 48%}" alt="...">
          </a>
          <div class="media-body">
            <h4 class="media-heading lead"><a href="{% url 'user' user_id=user.id %}">{{user.username}}</a></h4>
            <div>joined {{user.date_joined|naturaltime}}</div>
            <div class="user-stats pull-right">
              <span class="label label-default"><span class="glyphicon glyphicon-certificate"></span> {{user.num_ideas}} idea{% if user.num_ideas != 1 %}s{% endif %}</span>
              <span class="label label-default"><span class="glyphicon glyphicon-comment"></span> {{user.num_comments}} comment{% if user.num_comments != 1 %}s{% endif %}</span>
            </div>
          </div> <!-- /mediabody -->
        </div> <!-- /media -->
      </div> <!-- user -->

      {% endfor %}
      {% endif %}

    </div> <!-- col-md-12 -->
  </div> <!-- users-list -->
  
  {% if user_list.has_previous or user_list.has_next %}
  <div class="clearfix">
    <ul class="pager">
      {% if user_list.has_previous %}
        <li><a href="?page={{ user_list.previous_page_number }}">Previous page</a></li>
      {% endif %}

      {% if user_list.has_next %}
        <li><a href="?page={{ user_list.next_page_number }}">Next page</a></li>
      {% endif %}
    </ul>
    </div>
  {% endif %}

</div> <!-- /container -->



{% endblock %}

eureka/ideas/templates/ideas/users/view.html
{% extends "ideas/users/base.html" %}

{% block title %}Eureka - {{user_.username}}{% endblock %}

{% block content %}

{% load humanize %}
{% load gravatar %}

<div class="sub-navbar">
  <div class="container">
    <ol class="breadcrumb pull-left">
        <li><a href="{% url 'index' %}">Eureka</a></li>
        <li class="active"><a href="{% url 'users' %}">Users</a></li>
        <li class="active">{{user_.username}}</li>
    </ol>
    {% if user.id == user_.id %}
    <button type="button" class="btn btn-default btn-sm pull-right" onclick="window.location.href='{% url 'edit_user' %}'"><span class="glyphicon glyphicon-edit"></span> Change Password</button>
    {% endif %}
  </div>
</div>

<div class="container">
    <div class="row user-details">

        <div class="col-md-4">
            <div class="panel panel-default sidebar">
                <div class="panel-body">
                    <img src="{% gravatar_url user_.email 260 %}" alt="{{user_.username}} gravatar" class="img-rounded">
                    {% if user_.first_name %}
                    <h3>{{user_.first_name}} {{user_.last_name}}</h3>
                    {% else %}
                    <h3>{{user_.username}}</h3>
                    {% endif %}
                    <h4>{{user_.username}}</h4>
                    <hr>
                    <p><span class="glyphicon glyphicon-envelope"></span> <a href="mailto:{{user_.email}}">{{user_.email}}</a></p>
                    <p><span class="glyphicon glyphicon-time"></span> Joined {{user_.date_joined|naturaltime}}</p>
                    <hr>
                    <div class="row stats text-center">
                        <div class="col-md-4 col-sm-4">
                            <span>{{user_.idea_set.count}}</span>
                            <span class="description">idea{% if user_.idea_set.count != 1 %}s{% endif %}</span>
                        </div>
                        <div class="col-md-4 col-sm-4">
                            <span>{{user_.interest_set.count}}</span>
                            <span class="description">interest{% if user_.interest_set.count != 1 %}s{% endif %}</span>
                        </div>
                        <div class="col-md-4 col-sm-4">
                            <span>{{user_.comment_set.count}}</span>
                            <span class="description">comment{% if user_.interest_set.count != 1 %}s{% endif %}</span>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-body">
                    <ul class="nav nav-tabs">
                        <li class="{% if tab == 'ideas' %}active{% endif %}"><a href="{% url 'user' user_id=user_.id tab='ideas' %}"><i class="fa fa-lightbulb-o"></i> Ideas ({{user_.idea_set.count}})</a></li>
                        <li class="{% if tab == 'interests' %}active{% endif %}"><a href="{% url 'user' user_id=user_.id tab='interests' %}"><span class="glyphicon glyphicon-eye-open"></span> Interested in ({{user_.interest_set.count}})</a></li>
                        <li class="{% if tab == 'comments' %}active{% endif %}"><a href="{% url 'user' user_id=user_.id tab='comments' %}"><span class="glyphicon glyphicon-comment"></span> Comments ({{user_.comment_set.count}})</a></li>
                    </ul>

                    {% if list_items|length == 0 %}
                    <h4 class="lead">Ooops, it looks like there are no {{tab}} to show you.</h4>
                    {% else %}
                    
                        {% if tab == 'ideas' or tab == 'interests' %}
                        <div class="clearfix">
                            <ul class="nav nav-pills pull-right">
                                <li><a href="#" class="user-idea-filter filter-selected" data-filter="all">All</a></li>
                                <li><a href="#" class="user-idea-filter" data-filter="popular">Popular</a></li>
                                <li><a href="#" class="user-idea-filter" data-filter="approved">Approved</a></li>
                                <li><a href="#" class="user-idea-filter" data-filter="idle">Idle</a></li>
                                <li><a href="#" class="user-idea-filter" data-filter="rejected">Rejected</a></li>
                            </ul>
                        </div>
                        <hr class="small-hr">
                        {% endif %}

                        <div class="list-user-items">
                            {% if tab == 'ideas' or tab == 'interests' %}
                                {% for idea in list_items %}
                                <div class="list-user-item all{% if idea.state == 'A'%} approved{% elif idea.state == 'R' %} rejected{% else %} idle{% endif %}">
                                    {% if tab == 'interests' %}
                                    <a href="" class="pull-left">
                                        <img src="{% gravatar_url idea.user.email 32 %}" alt="...">
                                    </a>
                                    <h4 class="media-heading lead"><a href="{% url 'user' user_id=idea.user.id %}">{{idea.user.username}}</a></h4>
                                    {% endif %}
                                    <h4 class="media-heading lead">
                                        <a href="{% url 'idea' idea_id=idea.id %}">{{idea.title}}</a>
                                        <small class="text-muted"> {{idea.created|naturaltime}}</small></h4>
                                    <p>{{idea.text|truncatewords:"40"}}</p>
                                    <small class="text-muted">last edited {{idea.updated|naturaltime}}</small>

                                    <div class="idea-stats pull-right">
                                        {% if idea.state == "I"%}
                                        <span class="label label-warning">idle</span>
                                        {% elif idea.state == "A" %}
                                        <span class="label label-success">approved</span>
                                        {% else %}
                                        <span class="label label-danger">rejected</span>
                                        {% endif %}
                                        <span class="label label-default"><span class="glyphicon glyphicon-comment"></span> {{idea.interest_set.count}} interested</span>
                                        <span class="label label-default"><span class="glyphicon glyphicon-comment"></span> {{idea.comment_set.count}} comment{% if idea.comment_set.count != 1 %}s{% endif%}</span>
                                        <span class="label label-default"><span class="glyphicon glyphicon-thumbs-up"></span> 0 likes</span>
                                        <!-- <span class="label label-default">4 users interested</span> -->
                                    </div>

                                </div>
                                {% endfor %}

                            {% elif tab == 'comments' %}
                            <span class="label comment-timeline-label">Now</span>
                            <div class="comment-timeline">
                                <div class="timeline"></div>
                                {% for comment in list_items %}
                                <div class="comment-timeline-item {% if not forloop.counter|divisibleby:'2' %}timeline-left{% else %}timeline-right{% endif %}">
                                    <span class="label" title="{{comment.created}}">{{comment.created|naturaltime}}</span>
                                    <p>{{comment.text}}</p>
                                    <small><a href="{% url 'idea' idea_id=comment.idea.id %}">{{comment.idea.title}}</a></small>
                                </div>
                                {% endfor %}
                            </div>

                            <span class="label comment-timeline-label">{{user_.date_joined|naturaltime}}</span>

                            {% endif %}
                        </div>

                        {% if list_items.has_previous or list_items.has_next %}
                        <div>
                            <ul class="pager">
                                {% if list_items.has_previous %}
                                <li><a href="?page={{ list_items.previous_page_number }}">Previous page</a></li>
                                {% endif %}

                                {% if list_items.has_next %}
                                <li><a href="?page={{ list_items.next_page_number }}">Next page</a></li>
                                {% endif %}
                            </ul>
                        </div>
                        {% endif %}

                    {% endif %}
                </div>
            </div>
        </div>

    </div> <!-- /user-details -->
</div> <!-- /container -->

{% endblock %}